# Generated by Django 2.2.3 on 2019-07-26 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app11', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lip_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=250)),
                ('stream', models.CharField(max_length=205)),
                ('rollno', models.CharField(max_length=102)),
            ],
        ),
        migrations.CreateModel(
            name='Nyka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app11.Lip_Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='topic',
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
